const redundantPageTitle=document.getElementById('pageTitle');if(redundantPageTitle)redundantPageTitle.remove();
const eventTypeSelect=document.querySelector('#timelineForm select[name="type"]');if(eventTypeSelect)eventTypeSelect.innerHTML='<option>首次申请</option><option>再次申请</option><option>已通过</option><option>拒绝</option><option>合作</option>';
const priorityField=document.querySelector('#talentForm select[name="priority"]')?.closest('label');if(priorityField){const progressField=document.createElement('label');progressField.innerHTML='<span>进度</span><select name="progress"><option>未申请</option><option>已申请</option><option>已通过</option></select>';priorityField.insertAdjacentElement('afterend',progressField)}
const STORAGE_KEY='xingluo-talents-v1';
const colors={'抖音':'#dd765f','小红书':'#d58b74','快手':'#e0a14d','微博':'#6f8caf','B站':'#78a3b5','其他':'#81958c'};
const pageTitles={dashboard:'工作台',talents:'达人管理',projects:'项目汇总',add:'添加达人',reminders:'今日任务'};
const statusClass={'未申请':'status-new','等待通过':'status-waiting','已通过':'status-approved','已拒绝':'status-rejected'};
let activeStatus='全部',activeTag='全部',activeTask='全部',activeProject='all',currentTimelineId=null;
const iso=d=>d.toISOString().slice(0,10);const daysAgo=n=>{let d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()-n);return iso(d)};const future=n=>{let d=new Date();d.setDate(d.getDate()+n);return iso(d)};
const seed=[
 {id:1,nickname:'一颗桃桃',platform:'小红书',wechat:'taotao_2025',followers:186000,addDate:daysAgo(7),status:'等待通过',priority:'高价值',tags:['美妆','高转化'],stage:'好友申请',nextFollow:daysAgo(1),taskType:'重新联系',note:'内容质感很好',timeline:[{date:daysAgo(7),type:'第一次申请微信',result:'待回复',note:'已发送好友申请'},{date:daysAgo(4),type:'再次申请',result:'待回复',note:'二次申请，备注了品牌合作'}]},
 {id:2,nickname:'阿布的日常',platform:'抖音',wechat:'abu_daily88',followers:425000,addDate:daysAgo(5),status:'已通过',priority:'高价值',tags:['生活方式','直播'],stage:'报价沟通',nextFollow:daysAgo(0),taskType:'报价跟进',note:'近期有带货排期',timeline:[{date:daysAgo(5),type:'第一次申请微信',result:'同意',note:'当天通过好友'},{date:daysAgo(2),type:'回复合作',result:'继续跟进',note:'有合作兴趣，已发送产品资料'},{date:daysAgo(1),type:'报价确认',result:'待回复',note:'报价 8000 元，等待确认'}]},
 {id:3,nickname:'小鹿同学',platform:'快手',wechat:'xiaolu_kol',followers:98000,addDate:daysAgo(4),status:'等待通过',priority:'普通',tags:['穿搭','高互动'],stage:'好友申请',nextFollow:daysAgo(0),taskType:'重新联系',note:'粉丝互动率高',timeline:[{date:daysAgo(4),type:'第一次申请微信',result:'待回复',note:'已申请'}]},
 {id:4,nickname:'奶糖不甜',platform:'小红书',wechat:'naitang_note',followers:276000,addDate:daysAgo(3),status:'已通过',priority:'普通',tags:['美妆','图文'],stage:'合同推进',nextFollow:daysAgo(0),taskType:'合同跟进',note:'报价已确认',timeline:[{date:daysAgo(3),type:'第一次申请微信',result:'同意',note:''},{date:daysAgo(1),type:'报价确认',result:'同意',note:'确认合作价 4500 元'}]},
 {id:5,nickname:'陈大可',platform:'抖音',wechat:'dake_live',followers:680000,addDate:daysAgo(8),status:'已通过',priority:'高价值',tags:['直播','数码'],stage:'已建立合作',nextFollow:future(2),taskType:'合同跟进',note:'等待寄样',timeline:[{date:daysAgo(8),type:'第一次申请微信',result:'同意',note:''},{date:daysAgo(5),type:'回复合作',result:'同意',note:'确定直播合作'},{date:daysAgo(2),type:'合同跟进',result:'已完成',note:'合同已签署'}]},
 {id:6,nickname:'元气七七',platform:'微博',wechat:'qiqi_energy',followers:142000,addDate:daysAgo(0),status:'未申请',priority:'普通',tags:['母婴','生活方式'],stage:'待申请',nextFollow:future(1),taskType:'重新联系',note:'母婴生活类达人',timeline:[]},
 {id:7,nickname:'橘子汽水',platform:'B站',wechat:'orange_soda7',followers:315000,addDate:daysAgo(6),status:'已拒绝',priority:'暂不跟进',tags:['数码','测评'],stage:'暂停',nextFollow:'',taskType:'',note:'档期不合适',timeline:[{date:daysAgo(6),type:'第一次申请微信',result:'不同意',note:'近期无合作档期'}]}
];
function normalize(t){return {...t,priority:t.priority||'普通',tags:Array.isArray(t.tags)?t.tags:[],stage:t.stage||(t.status==='已通过'?'报价沟通':t.status==='等待通过'?'好友申请':t.status==='未申请'?'待申请':'暂停'),taskType:t.taskType||(t.status==='等待通过'?'重新联系':''),timeline:Array.isArray(t.timeline)?t.timeline:[]}}
function load(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(x)&&x.length?x.map(normalize):seed}catch{return seed}}let talents=load();
const save=()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(talents));const diff=s=>{if(!s)return -999;let a=new Date();a.setHours(0,0,0,0);return Math.floor((a-new Date(s+'T00:00:00'))/86400000)};const due=t=>t.priority!=='暂不跟进'&&t.nextFollow&&diff(t.nextFollow)>=0;const fmt=s=>s?new Intl.DateTimeFormat('zh-CN',{month:'short',day:'numeric'}).format(new Date(s+'T00:00:00')):'—';const esc=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const followers=n=>n>=10000?(n/10000).toFixed(n%10000?1:0)+'万粉丝':(n||'未填粉丝数');
function toast(s){let e=document.getElementById('toast');e.textContent=s;e.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.remove('show'),2000)}
function navigate(p){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===p));document.getElementById(p+'Page').classList.add('active');location.hash=p;if(p==='projects')renderProjects();if(p==='talents')renderTable();if(p==='reminders')renderReminders();}
function todayTasks(){return talents.filter(due)}
function renderAll(){renderDashboard();renderTags();renderTable();renderProjects();renderReminders();let n=todayTasks().length;document.getElementById('navReminderBadge').textContent=n;document.getElementById('notificationDot').style.display=n?'block':'none'}
function renderDashboard(){let tasks=todayTasks(),counts={重新联系:0,报价跟进:0,合同跟进:0};tasks.forEach(t=>counts[t.taskType]=(counts[t.taskType]||0)+1);document.getElementById('todayTotal').textContent=tasks.length+' 个';document.getElementById('taskContact').textContent=counts.重新联系;document.getElementById('taskQuote').textContent=counts.报价跟进;document.getElementById('taskContract').textContent=counts.合同跟进;document.getElementById('dashboardFollowList').innerHTML=tasks.length?tasks.slice(0,5).map(t=>`<div class="person-row"><div class="person-main"><span class="person-avatar" style="background:${colors[t.platform]}">${esc(t.nickname[0])}</span><div><strong>${esc(t.nickname)}</strong><small>${t.taskType} · ${t.priority}</small></div></div><span class="wait-time">${fmt(t.nextFollow)}</span><button class="mini-action" onclick="openTimeline(${t.id})">处理</button></div>`).join(''):'<div class="empty-state">今天没有到期任务 🎉</div>';let groups=[['未同意好友申请',t=>t.status==='等待通过'],['已同意好友申请',t=>t.status==='已通过'],['已建立合作',t=>t.stage==='已建立合作']];document.getElementById('dashboardPipeline').innerHTML=groups.map(([n,f])=>`<button onclick="openProject('${n}')"><span>${n}</span><strong>${talents.filter(f).length}</strong><i>→</i></button>`).join('')}
function renderTags(){let all=[...new Set(talents.flatMap(t=>t.tags))];document.getElementById('tagFilters').innerHTML=['全部',...all].map(x=>`<button class="tag-chip ${x===activeTag?'active':''}" data-tag="${esc(x)}">${esc(x)}</button>`).join('')}
function renderTable(){let q=document.getElementById('searchInput').value.trim().toLowerCase(),pri=document.getElementById('priorityFilter').value;let list=talents.filter(t=>(activeStatus==='全部'||t.status===activeStatus)&&(activeTag==='全部'||t.tags.includes(activeTag))&&(pri==='全部'||t.priority===pri)&&[t.nickname,t.wechat,t.note,...t.tags].join(' ').toLowerCase().includes(q));document.getElementById('tableCount').textContent=`共 ${list.length} 位达人`;document.getElementById('talentTableBody').innerHTML=list.length?list.map(t=>`<tr><td><div class="table-person"><span class="person-avatar" style="background:${colors[t.platform]||'#81958c'}">${esc(t.nickname[0])}</span><div><strong>${esc(t.nickname)}</strong><small>${t.platform} · ${followers(t.followers)}</small></div></div></td><td><div class="row-tags">${t.tags.slice(0,2).map(x=>`<span>${esc(x)}</span>`).join('')||'—'}</div></td><td><select class="priority-select priority-${t.priority}" onchange="changePriority(${t.id},this.value)"><option ${t.priority==='高价值'?'selected':''}>高价值</option><option ${t.priority==='普通'?'selected':''}>普通</option><option ${t.priority==='暂不跟进'?'selected':''}>暂不跟进</option></select></td><td>${esc(t.wechat)}</td><td><select class="status-select ${statusClass[t.status]}" onchange="changeStatus(${t.id},this.value)">${['未申请','等待通过','已通过','已拒绝'].map(s=>`<option ${s===t.status?'selected':''}>${s}</option>`).join('')}</select></td><td class="${due(t)?'overdue':''}">${fmt(t.nextFollow)}</td><td>${t.timeline.length?esc(t.timeline[t.timeline.length-1].type):'暂无记录'}</td><td><button class="timeline-button" onclick="openTimeline(${t.id})">时间轴 <b>${t.timeline.length}</b></button></td></tr>`).join(''):'<tr><td colspan="8"><div class="empty-state">没有符合条件的达人</div></td></tr>'}
const projects=[{key:'approved',name:'已同意好友申请',desc:'好友申请已通过，等待推进合作',filter:t=>t.status==='已通过'},{key:'waiting',name:'未同意好友申请',desc:'等待通过或尚未发起申请',filter:t=>['等待通过','未申请'].includes(t.status)},{key:'cooperating',name:'已建立合作',desc:'已达成明确合作的达人',filter:t=>t.stage==='已建立合作'}];
function renderProjects(){document.getElementById('projectCards').innerHTML=projects.map((p,i)=>`<button class="project-card ${activeProject===p.key?'active':''}" onclick="selectProject('${p.key}')"><i>${['✓','⌛','★'][i]}</i><span><small>${p.name}</small><strong>${talents.filter(p.filter).length}</strong><em>${p.desc}</em></span></button>`).join('');let p=projects.find(x=>x.key===activeProject),list=p?talents.filter(p.filter):talents;document.getElementById('projectListTitle').textContent=p?p.name:'全部达人';document.getElementById('projectListCount').textContent=list.length+' 位达人';document.getElementById('projectTalentList').innerHTML=list.length?list.map(t=>`<div class="project-person"><div class="person-main"><span class="person-avatar" style="background:${colors[t.platform]}">${esc(t.nickname[0])}</span><div><strong>${esc(t.nickname)}</strong><small>${t.platform} · ${t.tags.join(' / ')||'暂无标签'}</small></div></div><span class="priority-badge priority-${t.priority}">${t.priority}</span><span class="stage-label">${t.stage}</span><button class="mini-action" onclick="openTimeline(${t.id})">查看进展</button></div>`).join(''):'<div class="empty-state">该项目暂无达人</div>'}
function selectProject(k){activeProject=k;renderProjects()}function openProject(name){let p=projects.find(x=>x.name===name);activeProject=p?p.key:'all';navigate('projects')}
function renderReminders(){let list=todayTasks().filter(t=>activeTask==='全部'||t.taskType===activeTask);document.getElementById('reminderTotal').textContent=todayTasks().length;document.getElementById('reminderList').innerHTML=list.length?list.map(t=>`<div class="reminder-item"><div class="reminder-detail"><span class="person-avatar" style="background:${colors[t.platform]}">${esc(t.nickname[0])}</span><div><strong>${esc(t.nickname)} <span class="platform-tag">${t.platform}</span></strong><small>${t.taskType} · ${t.stage} · 到期 ${fmt(t.nextFollow)}</small></div></div><span class="priority-badge priority-${t.priority}">${t.priority}</span><div class="reminder-actions"><button class="mini-action" onclick="snooze(${t.id})">明天提醒</button><button class="primary-button" onclick="openTimeline(${t.id})">记录跟进</button></div></div>`).join(''):'<div class="empty-state">这一类任务已处理完毕</div>'}
function openTimeline(id){currentTimelineId=id;let t=talents.find(x=>x.id===id);if(!t)return;document.getElementById('timelineTitle').textContent=t.nickname+' · 跟进时间轴';document.getElementById('timelineSnapshot').innerHTML=`<span class="person-avatar" style="background:${colors[t.platform]}">${esc(t.nickname[0])}</span><div><strong>${t.platform} · ${esc(t.wechat)}</strong><small>${t.tags.map(x=>'#'+x).join(' ')||'暂无标签'}</small></div><span class="priority-badge priority-${t.priority}">${t.priority}</span>`;document.getElementById('timelineForm').elements.date.value=iso(new Date());document.getElementById('timelineForm').elements.nextFollow.value=t.nextFollow||future(1);renderTimeline(t);document.getElementById('timelineDrawer').classList.add('open');document.getElementById('drawerBackdrop').classList.add('open')}
function renderTimeline(t){let events=[...t.timeline].sort((a,b)=>b.date.localeCompare(a.date));document.getElementById('timelineList').innerHTML=events.length?events.map((e,i)=>`<div class="timeline-event"><i></i><div class="timeline-date">${fmt(e.date)}</div><div class="timeline-content"><div><strong>${esc(e.type)}</strong><span class="result result-${e.result}">${esc(e.result)}</span></div><p>${esc(e.note||'未填写备注')}</p></div></div>`).join(''):'<div class="empty-state">暂无跟进记录，从上方添加第一条记录</div>'}
function closeTimeline(){document.getElementById('timelineDrawer').classList.remove('open');document.getElementById('drawerBackdrop').classList.remove('open')}
function changePriority(id,v){let t=talents.find(x=>x.id===id);t.priority=v;save();renderAll();toast('优先级已更新')}
function changeStatus(id,v){let t=talents.find(x=>x.id===id),old=t.status;t.status=v;if(v==='等待通过'){t.stage='好友申请';t.taskType='重新联系';t.nextFollow=future(2);t.timeline.push({date:iso(new Date()),type:old==='未申请'?'首次申请':'再次申请',result:'待回复',note:'状态更新为等待通过'})}else if(v==='已通过'){t.stage='报价沟通';t.taskType='报价跟进';t.nextFollow=future(1);t.timeline.push({date:iso(new Date()),type:'已通过',result:'同意',note:'已通过微信好友申请'})}else if(v==='已拒绝'){t.stage='暂停';t.nextFollow='';t.taskType='';t.timeline.push({date:iso(new Date()),type:'拒绝',result:'不同意',note:'申请被拒绝'})}save();renderAll();toast('状态已更新并写入时间轴')}
function snooze(id){let t=talents.find(x=>x.id===id);t.nextFollow=future(1);save();renderAll();toast('已延后到明天')}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>navigate(b.dataset.page));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>navigate(b.dataset.go));document.getElementById('notificationButton').onclick=()=>navigate('reminders');document.getElementById('searchInput').oninput=renderTable;document.getElementById('priorityFilter').onchange=renderTable;
document.getElementById('statusFilters').onclick=e=>{if(!e.target.dataset.status)return;activeStatus=e.target.dataset.status;document.querySelectorAll('#statusFilters button').forEach(b=>b.classList.toggle('active',b===e.target));renderTable()};document.getElementById('tagFilters').onclick=e=>{if(!e.target.dataset.tag)return;activeTag=e.target.dataset.tag;renderTags();renderTable()};document.getElementById('taskFilters').onclick=e=>{if(!e.target.dataset.task)return;activeTask=e.target.dataset.task;document.querySelectorAll('#taskFilters button').forEach(b=>b.classList.toggle('active',b===e.target));renderReminders()};
document.getElementById('drawerClose').onclick=closeTimeline;document.getElementById('drawerBackdrop').onclick=closeTimeline;document.getElementById('toggleTimelineForm').onclick=()=>document.getElementById('timelineFormFields').classList.toggle('collapsed');
document.getElementById('timelineForm').onsubmit=e=>{e.preventDefault();let t=talents.find(x=>x.id===currentTimelineId),d=Object.fromEntries(new FormData(e.target));t.timeline.push({date:d.date,type:d.type,result:d.result,note:d.note.trim()});t.nextFollow=d.nextFollow;if(['首次申请','再次申请'].includes(d.type)){t.status='等待通过';t.stage='好友申请';t.taskType='重新联系'}else if(d.type==='已通过'){t.status='已通过';t.stage='报价沟通';t.taskType='报价跟进'}else if(d.type==='拒绝'){t.status='已拒绝';t.stage='暂停';t.taskType=''}else if(d.type==='合作'){t.status='已通过';t.stage=d.result==='已完成'||d.result==='同意'?'已建立合作':'合同推进';t.taskType='合同跟进'}save();renderAll();renderTimeline(t);e.target.elements.note.value='';toast('跟进记录已保存')};
document.getElementById('talentForm').onsubmit=e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target)),status=d.progress==='已申请'?'等待通过':d.progress,stage=d.progress==='未申请'?'待申请':d.progress==='已申请'?'好友申请':'报价沟通',taskType=d.progress==='已通过'?'报价跟进':'重新联系',timeline=d.progress==='未申请'?[]:[{date:iso(new Date()),type:d.progress==='已申请'?'首次申请':'已通过',result:d.progress==='已通过'?'同意':'待回复',note:'添加达人时记录的初始进度'}];talents.unshift(normalize({id:Date.now(),nickname:d.nickname.trim(),platform:d.platform,wechat:d.wechat.trim(),followers:+d.followers||0,addDate:iso(new Date()),status,priority:d.priority,tags:d.tags.split(/[,，]/).map(x=>x.trim()).filter(Boolean),stage,nextFollow:future(1),taskType,note:d.note.trim(),timeline}));save();e.target.reset();renderAll();navigate('talents');toast('达人添加成功')};
let label=new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(new Date());document.getElementById('todayText').textContent=label;document.getElementById('reminderDate').textContent=label;renderAll();let hash=location.hash.slice(1);navigate(pageTitles[hash]?hash:'dashboard');
