import { bulkConvertTalentResources, bulkUpdateTalentResourcePriority, convertTalentResource } from "@/app/(app)/resources/actions";
import { getTalentPlatformLabel, getTalentPriorityLabel, TALENT_PRIORITIES, TALENT_PRIORITY_LABELS } from "@/lib/constants";
import type { Tables } from "@/types/database";

type Props = { resources: Tables<"talent_resources">[]; status: "new" | "converted" };

export function ResourceTable({ resources, status }: Props) {
  return <form className="mt-5 overflow-hidden rounded-2xl border border-[#e7ebe8] bg-white shadow-sm">
    {status === "new" ? <div className="flex flex-col gap-3 border-b border-[#edf0ee] bg-[#f8faf8] p-4 sm:flex-row sm:items-center"><p className="text-sm font-medium text-[#35443e]">批量处理所选资源</p><select className="rounded-lg border border-[#dfe5e1] bg-white px-3 py-2 text-sm" defaultValue="normal" name="bulk_priority">{TALENT_PRIORITIES.map(value => <option key={value} value={value}>{TALENT_PRIORITY_LABELS[value]}</option>)}</select><button className="rounded-lg border border-[#31594b] px-3 py-2 text-sm font-medium text-[#31594b]" formAction={bulkUpdateTalentResourcePriority}>修改优先级</button><button className="rounded-lg bg-[#31594b] px-3 py-2 text-sm font-semibold text-white" formAction={bulkConvertTalentResources}>批量转正式达人</button><span className="text-xs text-slate-400">单次最多 100 条</span></div> : null}
    <div className="overflow-x-auto"><table className="w-full min-w-[940px] text-left text-sm"><thead className="bg-[#f8faf8] text-xs text-[#668074]"><tr>{status === "new" ? <th className="w-12 px-4 py-3">选择</th> : null}<th className="px-5 py-3">达人</th><th className="px-4 py-3">平台</th><th className="px-4 py-3">赛道</th><th className="px-4 py-3">优先级</th><th className="px-4 py-3">来源</th><th className="px-5 py-3 text-right">操作</th></tr></thead><tbody className="divide-y divide-[#edf0ee]">{resources.map(item => <tr key={item.id}>{status === "new" ? <td className="px-4 py-4"><input aria-label={`选择 ${item.nickname}`} className="size-4 accent-[#31594b]" name="resource_ids" type="checkbox" value={item.id} /></td> : null}<td className="px-5 py-4"><strong>{item.nickname}</strong><span className="mt-1 block text-xs text-slate-400">{item.platform_account || "未填写账号"}</span></td><td className="px-4 py-4">{getTalentPlatformLabel(item.primary_platform)}</td><td className="px-4 py-4">{item.category}</td><td className="px-4 py-4">{getTalentPriorityLabel(item.priority)}</td><td className="px-4 py-4">{item.source || "—"}</td><td className="px-5 py-4 text-right">{item.status === "new" ? <button className="rounded-lg bg-[#31594b] px-3 py-2 text-xs font-semibold text-white" formAction={convertTalentResource} name="resource_id" value={item.id}>转为正式达人</button> : <span className="text-xs text-emerald-700">已转换</span>}</td></tr>)}</tbody></table></div>
  </form>;
}
