import Link from "next/link";

import { bulkConvertTalentResources, bulkUpdateTalentResourcePriority, convertTalentResource } from "@/app/(app)/resources/actions";
import { BulkCreateTaskButton } from "@/components/resources/bulk-create-task-button";
import { BulkDeleteButton } from "@/components/resources/bulk-delete-button";
import { getResourceProcessingStatusLabel, getTalentPlatformLabel, getTalentPriorityLabel, TASK_TYPES, TASK_TYPE_LABELS, TALENT_PRIORITIES, TALENT_PRIORITY_LABELS } from "@/lib/constants";
import { formatDateTime, toShanghaiTomorrowDateTimeLocalValue } from "@/lib/formatters/date";
import type { Tables } from "@/types/database";

type Props = { resources: Tables<"talent_resources">[]; status: "new" | "converted" };

export function ResourceTable({ resources, status }: Props) {
  return <form className="mt-5 overflow-hidden rounded-2xl border border-[#e7ebe8] bg-white shadow-sm">
    {status === "new" ? <div className="border-b border-[#edf0ee] bg-[#f8faf8] p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><p className="text-sm font-medium text-[#35443e]">批量处理所选资源</p><select className="rounded-lg border border-[#dfe5e1] bg-white px-3 py-2 text-sm" defaultValue="normal" name="bulk_priority">{TALENT_PRIORITIES.map(value => <option key={value} value={value}>{TALENT_PRIORITY_LABELS[value]}</option>)}</select><button className="rounded-lg border border-[#31594b] px-3 py-2 text-sm font-medium text-[#31594b]" formAction={bulkUpdateTalentResourcePriority}>修改优先级</button><button className="rounded-lg bg-[#31594b] px-3 py-2 text-sm font-semibold text-white" formAction={bulkConvertTalentResources}>批量转正式达人</button><BulkDeleteButton /><span className="text-xs text-slate-400">单次最多 100 条</span></div><div className="mt-4 grid gap-3 border-t border-[#e3e9e5] pt-4 md:grid-cols-2 lg:grid-cols-5"><label className="grid gap-1 text-xs font-medium text-[#557064]">任务类型<select className="rounded-lg border border-[#dfe5e1] bg-white px-3 py-2 text-sm text-[#26332e]" defaultValue="follow_up" name="bulk_task_type">{TASK_TYPES.map(value => <option key={value} value={value}>{TASK_TYPE_LABELS[value]}</option>)}</select></label><label className="grid gap-1 text-xs font-medium text-[#557064]">执行时间<input className="rounded-lg border border-[#dfe5e1] bg-white px-3 py-2 text-sm text-[#26332e]" defaultValue={toShanghaiTomorrowDateTimeLocalValue()} name="bulk_task_due_at" required type="datetime-local" /></label><label className="grid gap-1 text-xs font-medium text-[#557064]">下一步动作<input className="rounded-lg border border-[#dfe5e1] bg-white px-3 py-2 text-sm text-[#26332e]" defaultValue="联系达人" maxLength={500} name="bulk_next_action" required /></label><label className="grid gap-1 text-xs font-medium text-[#557064]">任务备注<input className="rounded-lg border border-[#dfe5e1] bg-white px-3 py-2 text-sm text-[#26332e]" maxLength={2000} name="bulk_task_notes" placeholder="可选" /></label><div className="flex items-end"><BulkCreateTaskButton /></div></div></div> : null}
    <div className="overflow-x-auto"><table className="w-full min-w-[1160px] text-left text-sm"><thead className="bg-[#f8faf8] text-xs text-[#668074]"><tr>{status === "new" ? <th className="w-12 px-4 py-3">选择</th> : null}<th className="px-5 py-3">达人</th><th className="px-4 py-3">平台</th><th className="px-4 py-3">赛道</th><th className="px-4 py-3">优先级</th><th className="px-4 py-3">处理状态</th><th className="px-4 py-3">下次处理</th><th className="px-4 py-3">来源</th><th className="px-5 py-3 text-right">操作</th></tr></thead><tbody className="divide-y divide-[#edf0ee]">{resources.map(item => <tr className="transition hover:bg-[#f8faf8]" key={item.id}>{status === "new" ? <td className="px-4 py-4"><input aria-label={`选择 ${item.nickname}`} className="size-4 accent-[#31594b]" name="resource_ids" type="checkbox" value={item.id} /></td> : null}<td className="px-5 py-4"><Link className="group inline-flex flex-col" href={`/resources/${item.id}`}><strong className="text-[#26332e] group-hover:text-[#31594b] group-hover:underline">{item.nickname}</strong><span className="mt-1 text-xs text-slate-400">{item.platform_account || "未填写账号"}</span><span className="mt-1 text-xs font-medium text-[#668074] opacity-0 transition group-hover:opacity-100">查看详情 →</span></Link></td><td className="px-4 py-4">{getTalentPlatformLabel(item.primary_platform)}</td><td className="px-4 py-4">{item.category}</td><td className="px-4 py-4">{getTalentPriorityLabel(item.priority)}</td><td className="px-4 py-4">{getResourceProcessingStatusLabel(item.processing_status ?? "pending_add")}</td><td className="px-4 py-4 text-xs text-slate-600">{item.next_action_at ? formatDateTime(item.next_action_at) : "未安排"}</td><td className="px-4 py-4">{item.source || "—"}</td><td className="px-5 py-4 text-right">{item.status === "new" ? <button className="rounded-lg bg-[#31594b] px-3 py-2 text-xs font-semibold text-white" formAction={convertTalentResource} name="resource_id" value={item.id}>转为正式达人</button> : <span className="text-xs text-emerald-700">已转换</span>}</td></tr>)}</tbody></table></div>
  </form>;
}
